name: CI for instaui-tdesign
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main


env:
  NPM_DIR_NAME: npm-src

jobs:
  testing:
    name: testing web app
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12']
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: set up npm-src and testing
        uses: instaui-python/org-ci-config/.github/actions/npm-env@main
        with:
          npm_dir_name : ${{ env.NPM_DIR_NAME }}
          test_cmd: ''

      - name: set up python and playwright and install the project
        uses: instaui-python/org-ci-config/.github/actions/playwright-python-env@main

      - name: run tests
        timeout-minutes: 2
        run: |
          uv run --no-sources pytest __tests
        shell: bash

 